project_name: qrypt
dist: release

before:
  hooks:
    - make -j6 dist

builds: []

archives:
  - id: linux-amd64
    files: [dist/qrypt-linux-amd64]
    name_template: "{{ .ProjectName }}_{{ .Version }}_linux_amd64"
    format: tar.gz
  - id: linux-arm64
    files: [dist/qrypt-linux-arm64]
    name_template: "{{ .ProjectName }}_{{ .Version }}_linux_arm64"
    format: tar.gz
  - id: darwin-amd64
    files: [dist/qrypt-darwin-amd64]
    name_template: "{{ .ProjectName }}_{{ .Version }}_darwin_amd64"
    format: tar.gz
  - id: darwin-arm64
    files: [dist/qrypt-darwin-arm64]
    name_template: "{{ .ProjectName }}_{{ .Version }}_darwin_arm64"
    format: tar.gz
  - id: windows-amd64
    files: [dist/qrypt-windows-amd64.exe]
    name_template: "{{ .ProjectName }}_{{ .Version }}_windows_amd64"
    format: zip
  - id: windows-arm64
    files: [dist/qrypt-windows-arm64.exe]
    name_template: "{{ .ProjectName }}_{{ .Version }}_windows_arm64"
    format: zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+"
      order: 0
    - title: Bug fixes
      regexp: "^.*fix[(\\w)]*:+"
      order: 1
    - title: Others
      order: 999
