version: 2

project_name: qrypt
dist: release

builds:
  - id: prebuilt
    skip: true

release:
  replace_existing_artifacts: true
  extra_files:
    - glob: dist/qrypt_*.tar.gz
    - glob: dist/qrypt_*.zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  extra_files:
    - glob: dist/qrypt_*.tar.gz
    - glob: dist/qrypt_*.zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+"
      order: 0
    - title: Bug fixes
      regexp: "^.*fix[(\\w)]*:+"
      order: 1
    - title: Others
      order: 999
